allow `cat` of regression diff to fail, print a warning instead
this will allow the regression test results to all be reported even if there is such a huge difference between the dynamic and baseline that the system utilities cannot print it

see: https://github.com/ReactionMechanismGenerator/RMG-Py/pull/2316#issuecomment-1654884245

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -273,7 +273,7 @@ jobs:
               export FAILED=Yes
             fi
             echo "" # blank line so next block is interpreted as markdown
-            cat "$regr_test-core.log"
+            cat "$regr_test-core.log" || (echo "Dumping the whole log failed, please download it from GitHub actions. Here are the first 100 lines:" && head -n100 "$regr_test-core.log")
             echo "</details>"
             echo "<details>"
             if python-jl scripts/checkModels.py \
@@ -290,7 +290,7 @@ jobs:
               export FAILED=Yes
             fi
             echo "" # blank line so next block is interpreted as markdown
-            cat "$regr_test-edge.log"
+            cat "$regr_test-edge.log" || (echo "Dumping the whole log failed, please download it from GitHub actions. Here are the first 100 lines:" && head -n100 "$regr_test-core.log")
             echo "</details>"
 
             # Check for Regression between Reference and Dynamic (skip superminimal)
