CI: run codecov even if regression tests fail.
Could be helpful to know code coverage even in cases when the 
regression tests are failing - sometimes (hopfully often!) a 
"regression" is an improvement, and a "fail" is thus a success.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -121,7 +121,7 @@ jobs:
 
       # Regression Testing - Test Execution
       - name: Regression Tests - Execution
-        id: regression
+        id: regression-execution
         timeout-minutes: 60
         run: |
           for regr_test in aromatics liquid_oxidation nitrogen oxidation sulfur superminimal RMS_constantVIdealGasReactor_superminimal RMS_CSTR_liquid_oxidation RMS_liquidSurface_ch4o2cat;
@@ -141,7 +141,7 @@ jobs:
 
       # Upload Regression Results as Failed if above step failed
       - name: Upload Failed Results
-        if: ${{ failure() && steps.regression.conclusion == 'failure' }}
+        if: ${{ failure() && steps.regression-execution.conclusion == 'failure' }}
         uses: actions/upload-artifact@v3
         with:
           name: failed regression results ${{ matrix.os }} ${{ matrix.libstdcxx-ng }}
@@ -256,8 +256,9 @@ jobs:
             exit 1
           fi
 
-      # Install and Call codecov only if ALL the tests were successful
+      # Install and Call codecov only if the tests were successful (permitting failures in the regression comparison tests)
       - name: Code coverage install and run
+        if: success() || ( failure() && steps.regression-execution.conclusion == 'success' )
         run: |
           mamba install -y -c conda-forge codecov
           codecov
