Continue on errors for some CI steps
We want the subsequent job step to run even if the unit tests fail,
but we want the overall job to be marked as a failure.
So we use conditionals on the subsequent steps,
rather than "continue-on-error" settings.

Installing MOPAC, however, is allowed to fail entirely
because it will always do so on pull requests from forks
(that don't have access to the secrets).
And it times out after a minute, as it has a habit
of hanging if you get it wrong.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -24,6 +24,8 @@ jobs:
           conda info
           conda list
       - name: Install mopac
+        timeout-minutes: 1
+        continue-on-error: true
         run: yes 'Yes' | ${CONDA_PREFIX}/bin/mopac $MOPACKEY > /dev/null
       - name: Install and compile RMG
         run: |
@@ -35,8 +37,10 @@ jobs:
       - name: Unit tests
         run: make test-unittests
       - name: Functional tests
+        if: ${{ success() || failure() }} # Run even if the unit tests failed (but not if they were cancelled)
         run: make test-functional
       - name: Database tests
+        if: ${{ success() || failure() }} # Run even if the functional tests failed (but not if they were cancelled)
         run: make test-database
       - name: Code coverage
         run: codecov
